# Generated by Django 3.2.7 on 2021-09-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('records', models.PositiveIntegerField()),
                ('method', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data_breach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_breaches.databreach')),
            ],
        ),
        migrations.AddField(
            model_name='databreach',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_breaches.entity'),
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(max_length=30)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_breaches.entity')),
            ],
            options={
                'unique_together': {('organization_type', 'entity')},
            },
        ),
    ]
