# Generated by Django 3.2.7 on 2021-09-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_breaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='data_breach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='data_breaches.databreach'),
        ),
    ]
