# Generated by Django 3.2.7 on 2021-09-28 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_breaches', '0003_auto_20210911_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databreach',
            name='records',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970)]),
        ),
    ]
